import { EditorThemeClasses } from 'lexical'

const editorTheme: EditorThemeClasses = {
  root: 'p-4 border-slate-500 w-full border-2 rounded h-full min-h-[200px] focus:outline-none focus-visible:border-black',
  ltr: 'ltr',
  rtl: 'rtl',
  placeholder: 'editor-placeholder',
  paragraph: 'mb-2 relative',
  quote: 'border-l-4 border-indigo-400 pl-2 italic  dark:text-white',
  heading: {
    h1: 'text-3xl font-extrabold dark:text-white',
    h2: 'text-2xl font-bold dark:text-white',
    h3: 'text-xl font-bold dark:text-white',
    h4: 'text-lg font-bold dark:text-white',
    h5: 'font-bold dark:text-white',
  },
  list: {
    nested: {
      listitem: 'pl-5 mt-2 space-y-1 list-none dark:text-white',
    },
    ol: 'max-w-md space-y-1 text-gray-500 list-decimal list-inside marker:text-indigo-600 dark:text-white dark:marker:text-indigo-400',
    ul: 'max-w-md space-y-1 text-gray-500 list-disc list-inside marker:text-indigo-600 dark:text-white dark:marker:text-indigo-400',
    listitem: 'dark:text-white',
  },
  image: 'editor-image',
  link: 'font-medium text-indigo-600 dark:text-indigo-400 hover:underline',
  text: {
    bold: 'font-bold',
    italic: 'italic',
    overflowed: 'editor-text-overflowed',
    hashtag: 'editor-text-hashtag',
    underline: 'underline',
    strikethrough: 'line-through',
    underlineStrikethrough: 'underline line-through',
    code: 'font-mono text-[94%] bg-gray-100 dark:bg-gray-600 dark:text-white p-1 rounded',
  },
  code: 'bg-[#EEF1F6] text-ctp-text dark:bg-[#23273B] font-mono block py-2 px-10  m-0 mt-2 mb-2 tab-2 overflow-x-auto relative before:absolute before:content-[attr(data-gutter)] beforewbg-gray-200 dark:before:bg-gray-700 before:left-0 before:top-0 before:p-2 before:min-w-[25px] before:whitespace-pre-wrap before:text-right after:content-[attr(data-highlight-langrage)] after:right-3 after:absolute',
  codeHighlight: {
    atrule: 'text-ctp-green',
    attr: 'text-ctp-green',
    boolean: 'text-ctp-peach',
    builtin: 'text-ctp-red',
    cdata: 'text-ctp-green',
    char: 'text-ctp-green',
    class: 'text-ctp-teal',
    'class-name': 'text-ctp-yellow',
    comment: 'text-ctp-overlay2',
    constant: 'text-ctp-peach',
    deleted: 'text-ctp-red',
    doctype: 'text-ctp-red',
    entity: 'text-ctp-red',
    function: 'text-ctp-blue',
    important: 'text-ctp-red',
    inserted: 'text-ctp-green',
    keyword: 'text-ctp-mauve',
    namespace: 'text-ctp-mauve',
    number: 'text-ctp-peach',
    operator: 'text-ctp-sky',
    prolog: 'text-ctp-red',
    property: 'text-ctp-teal',
    punctuation: 'text-ctp-subtext2',
    regex: 'text-ctp-pink',
    selector: 'text-ctp-blue',
    string: 'text-ctp-green',
    symbol: 'text-ctp-flamingo',
    tag: 'text-ctp-teal',
    url: 'text-ctp-saphire',
    variable: 'text-ctp-mauve',
    literal: 'text-ctp-peach',
  },
  table: 'table-auto w-full text-left rtl:text-right',
  tableRow: 'border-y border-gray-400',
  tableCell: 'border-x p-2 border-gray-400',
  tableHeader: 'p-3 font-bold text-md bg-gray-200 dark:bg-gray-500',
}

export default editorTheme
